apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: x-istio-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/istio/istio
    path: manifests/charts/istio-operator
    targetRevision: master
    helm:
      parameters:
        - name: enableCRDTemplates
          value: 'true'
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: istio-operator
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
